### ISSUE TITLE
Capstone PR

### ISSUE THREAD

**Issue by evansnyamekye** [HtetWaiYan7191/capstone-project#3]
### Review on Project-Peer to peer 
**HTML**
- The layout of  your code is good.
- Good design. 
- God use of html mackup. 
- good use of bootstrap. 
- Good use creating different page for capstone PR. 
- You need to fill up your alt id. 
-Kindly make good use of percentage instead of fix measurement(%).
-Good design kindly check the breakpoint of the design since it is overlapping.
**STYLES.CSS**
-Good use of CSS and flex box properties. 

thank you 😀 . 💯

**Comment by HtetWaiYan7191** [comment]
Thank you very much for your reviews
